### ISSUE TITLE
Make `ruststrap.sh` accept a `--target` flag

### ISSUE THREAD

**Issue by japaric** [japaric/ruststrap#11]
This would allow cross bootstrapping Rust to other ARM ABIs, like the `arm-unknown-linux-gnueabi` (and maybe the R-Pi). If the flag is omitted, the `arm-unknown-linux-gnueabihf` ABI will be used (this is the current behaviour).

I won't be able to test the produced compiler for the `gnueabi` ABI  nor for the R-Pi. So I need testers!

**Comment by pnathan** [comment]
I can dedicate a RPi for doing rust testing, I am sure. the rust community really needs a nightly rpi build (and, frankly, a build of the 1.x.y line too. :) )

Please let me know where I can download the latest and run the job.

**Comment by japaric** [comment]
Although I didn't implement the `--target` flag, you can cross compile the rust compiler for other archs/triples by setting a few environment variables.

> I can dedicate a RPi for doing rust testing,

That'd be great!

> Please let me know where I can download the latest and run the job.

Cross compiling an ARM**v7** compiler (which doesn't work with the RPi) is easy (it takes a few hours though), these are the steps I use:

``` shell
# On your x86_64 machine/laptop
# You only need to have `deboostrap` installed
$ sudo su
$ cd /mnt
# build an Ubuntu 14.04 chroot under the `ubuntu` folder
$ debootstrap --variant=buildd --arch=amd64 trusty ubuntu http://archive.ubuntu.com/ubuntu/
$ cd ubuntu
$ wget https://raw.githubusercontent.com/japaric/ruststrap/master/ruststrap.sh
$ chmod +x ruststrap.sh
# log into the ubuntu chroot
$ systemd-nspawn
# I'm going to use `$$` to denote the shell inside the chroot
$$ cd /
# you can pass the hash of the last nightly (1)
$$ ./ruststrap.sh 4e4e8cff1697ec79bcd0a1e45e63fb2f54a7ea28
$$ logout
# this is the product tarball
$ ls /mnt/ubuntu/rust-*
/mnt/ubuntu/rust-2015-01-14-170c439-arm-unknown-linux-gnueabihf-67b6c07468fcb7c9cc1cf8c67eefbc0d4cb10169.tar.gz
```

(1) if the hash is omitted the script builds git HEAD. You can find the hash of the nigthlies [here]

[here]: http://buildbot.rust-lang.org/builders/nightly-dist-rustc-linux

Unpacking the tarball in the `/usr/local` directory of your ARM device should just work.

Now to make it work with the RPi, you need two changes:

- You may need to use a different triple, you can do that by setting these [environment variables]. I think the RPi also uses the arm-unknown-linux-gnueabihf triple though, you can check by looking at the output of `gcc -v` or `clang -v`.

[environment variables]: https://github.com/japaric/ruststrap/blob/2e2c22502a853d357939bebea8daa31701662cbe/ruststrap.sh#L15-16

- You need to modify this [line] of ruststrap to install an RPi g++ cross compiler instead of an ARMv7 one. After a quick search, I couldn't find an official RPi cross compiler package for Ubuntu. You probably know better than I how to install one though.

[line]: https://github.com/japaric/ruststrap/blob/2e2c22502a853d357939bebea8daa31701662cbe/ruststrap.sh#L38

> I can also provide hosting or other infrastructural aspects if that is an issue.

That'd be nice! Actually, I don't have where to host the ARM nightlies at the moment, which is one of the reasons I stopped uploading them. The other reason is that I haven't manage to cross compile a newer cargo binary for ARM (it has become really hard now that cargo has more native dependencies, also some dependencies just [refuse to cross compile] at all!), and without an up to date ARM cargo binary binary, I can't bootstrap nightly ARM cargo binaries.

[refuse to cross compile]: https://github.com/sfackler/rust-openssl/blob/cfe9df78fa5c341671a55a6945dedb91c21af8b6/openssl-sys/src/build.rs#L8-9

Anyhow, do let me know if you are going to try cross compiling a RPi rustc binary or if you encounter any issue in the process. And if you offer me some space to host the ARM nightlies, I'd gladly take it :-).

P.S. Btw, you can find me on IRC (#rust-internals) under the same nick, if you'll like to chat.

**Comment by pnathan** [comment]
I have a node in Digital Ocean that can host - it's more of a generic
server. I'm also in the process of standing up a Azure account to handle
larger archives (debs, dockerfiles, etc).

Would Azure hosting be amenable? (providing I can figure out a simple way
to share out keys for upload).

**Comment by japaric** [comment]
I think either one is fine, as long as the file upload can be automated.

**Comment by pnathan** [comment]
Is there a pre-existing CI resource that could be leveraged here?

Looking at Azure, I should be able to develop a simple upload script setup.
I'm leery of giving out keys to the Azure blob, as there isn't any easy way
of limiting size of blobs.

**Comment by japaric** [comment]
> Is there a pre-existing CI resource that could be leveraged here?

If you mean CI services like travis, they'll likely to timeout before the build process finish.

Btw, right now I'm trying to setup build automation in my ARM device (#9) and hook it up with a shared dropbox folder. ([Dropbox-Uploader] is really nice!)

[Dropbox-Uploader]: https://github.com/andreafabrizi/Dropbox-Uploader

**Comment by japaric** [comment]
I don't think I'll add this `--target` flag since the env variables should be good enough. So I'm closing this.

@pnathan I've uploaded rustc and cargo nightlies for ARM to my dropbox folder, but I don't know if they'll run on the RPi. If you want to help me test, see #18 (links are over there)
