### ISSUE TITLE
Test if the produced binaries actually run on the Raspberry Pi

### ISSUE THREAD

**Issue by japaric** [japaric/ruststrap#18]
I built the nightlies on my ODROID XU, which is an ARMv7 device. But, I don't know if the produced binaries are generic enough (i.e. if they don't contain ARMv7 specific instructions) to run on the RPi. And I don't have an RPi to actually test.

So I need help from RPi owners to confirm this. Binaries [here].

[here]: https://www.dropbox.com/sh/qfbt03ys2qkhsxs/AACxFoD1OrxDXURzj5wX0IYUa?dl=0

To test `rustc`:

``` shell
$ mkdir rust
$ cd rust
$ mv $RUST_TARBALL .
$ tar xzf $RUST_TARBALL
$ LD_LIBRARY_PATH=$LD_LIBRARY_PATH:lib bin/rustc -V
rustc 1.0.0-dev (a637365b1 2015-01-26 22:19:44 +0000)
```

If that succeeded, you can test `cargo` with:

``` shell
$ mkdir cargo
$ ls
cargo  rust
$ cd cargo
$ mv $CARGO_TARBALL .
$ tar xzf $CARGO_TARBALL
$ cd ..
$ LD_LIBRARY_PATH=$LD_LIBRARY_PATH:rust/lib:cargo/lib PATH=$PATH:rust/bin cargo/bin/cargo -V
cargo 0.0.1-pre (453ae9f 2015-01-29 00:56:56 +0000)
```

You can remove the `rust` and `cargo` directories afterwards.

If you encounter any error, please post it here!

**Comment by Novacha** [comment]
It seems the version of rust in that dropbox folder is linked to a newer version of glibc than the current Raspbian distro provides. I get the following errors when trying to run `LD_LIBRARY_PATH=$LD_LIBRARY_PATH:lib bin/rustc -V`:

```
pi@raspberrypi ~/ruststrap/rust $ LD_LIBRARY_PATH=$LD_LIBRARY_PATH:lib bin/rustc -V
bin/rustc: /lib/arm-linux-gnueabihf/libc.so.6: version `GLIBC_2.18' not found (required by lib/libstd-4e7c5e5c.so)
bin/rustc: /usr/lib/arm-linux-gnueabihf/libstdc++.so.6: version `GLIBCXX_3.4.20' not found (required by lib/librustc_llvm-4e7c5e5c.so)
bin/rustc: /lib/arm-linux-gnueabihf/libc.so.6: version `GLIBC_2.15' not found (required by lib/librustc_llvm-4e7c5e5c.so)
```

The latest version of glibc on Raspbian is 2.13:

```
pi@raspberrypi ~/ruststrap/rust $ sudo dpkg -l | grep libc6
ii  libc6:armhf                           2.13-38+rpi2+deb7u7                     armhf        Embedded GNU C Library: Shared libraries
ii  libc6-dev:armhf                       2.13-38+rpi2+deb7u7                     armhf        Embedded GNU C Library: Development Libraries and Header Files
```

As a lot of packages are out of date on Raspbian, building glibc from source will be quite difficult. The distro version I used was:

```
pi@raspberrypi ~/ruststrap/rust $ cat /etc/issue
Raspbian GNU/Linux 7 \n \l
```

I have a spare Raspberry PI lying around so I will try to run the rustc arm binaries on one of the other supported Raspberry PI OSs.

**Comment by japaric** [comment]
@Novacha Aha! IIRC this is one of the reasons the buildbots run an old version of Ubuntu (12.04?): to lower the glibc dependency requirement. Let me build rust in an an Ubuntu 12.04 chroot to lower the glibc version to 2.15 (I hope that's low enough). I'll ping you when I get the tarball ready. And thanks for the report :+1:!

**Comment by shavounet** [comment]
Yep, I've got the exact same issue as @Novacha !
I don't know if my local (working) version of rust is old enough (something like rust-0.12.0-pre-e0bd16c) to be relevent, but here is the result for cargo : 
```
pi@raspberrypi ~/projects/lib/rust/cargo-snapshot_453ae9f $ LD_LIBRARY_PATH=$LD_LIBRARY_PATH:lib bin/cargo -V
bin/cargo: /usr/lib/arm-linux-gnueabihf/libcurl.so.4: version `CURL_OPENSSL_4' not found (required by bin/cargo)
bin/cargo: /lib/arm-linux-gnueabihf/libc.so.6: version `GLIBC_2.18' not found (required by bin/cargo)
```

**Comment by japaric** [comment]
@shavounet Could you tell me the versions of the `libc` and `libcurl` libraries you have installed? And also which OS you are running on the RPi (raspian?).

(I'm still trying to figure out the best way to build against older libraries without complicating the automation that I've already set up.)

**Comment by plugwash** [comment]
hi guys, raspbian cofounder here.

Firstly on glibc versions, Debian (and hence raspbian) wheezy despite being newer than precise has an older glibc version, specifically 2.13-38+deb7u7 in Debian wheezy and 2.13-38+rpi2+deb7u7 in raspbian wheezy. 

Secondly building in an armv7 environment but trying to target armv6 doesn't tend to work out very well. The problem (at least with C) is even if you tell the compiler to build for armv6 you usually end up linking things like startup code that were built for armv7 and so you end up with armv7 stuff in the resulting binary.

In general if you want to build stuff for raspbian using a raspbian chroot is the reccommended approach. You can create such a chroot on your debian or ubuntu armhf system with.

debootstrap --no-check-gpg --arch=armhf wheezy /chroots/wheezy http://mirrordirector.raspbian.org/raspbian

**Comment by shavounet** [comment]
I've got the same libc and OS (Raspbian 7 yes) than @Novacha and libcurl is 7.26.0-1+wheezy11.

Thanks for the tips @plugwash ! In this domain my knowledge is limited, but @japaric, if I can help you build those binaries, it would be my pleasure.

**Comment by Novacha** [comment]
Just a quick note: The Raspberry Pi foundation just released their [Raspberry Pi V2](http://www.raspberrypi.org/raspberry-pi-2-on-sale/). Aside from a memory upgrade (to 1GB), it now has a quad-core **ARMv7** processor. 

I have ordered one which should arrive within the next few days. When it arrives I will try to run the ruststrap built rust on it. I'll keep you updated!

**Comment by japaric** [comment]
@plugwash Thanks for the input! I'm following your suggested approach of building rust in the raspbian chroot, but it's harder than I thought! The ARM nightlies/stage0 that I already have require a glibc-2.18+ to run (duh!), so I can't use those to bootstrap rust inside the raspbian chroot. What I'm doing now is cross-compiling a new ARM rustc inside a x86_64 precise/wheezy (old glibc) chroot but I'm having problems beetwen meeting the build dependencies (gcc-4.7+ and arm-gcc-4.7 or clang-3.1+ without updating glibc) and making the rust build system prefer clang over gcc. But, I think I'm close now.

@shavounet 

> if I can help you build those binaries, it would be my pleasure.

If we ultimately need to bootstrap rust in the RPi, I'll gladly take your help. But, first we need a relatively new rustc than runs on the RPi.

@Novacha 

> I have ordered one which should arrive within the next few days. When it arrives I will try to run the ruststrap built rust on it. I'll keep you updated!

Awesome! If it can use an OS with a newer glibc version (>=2.18), the existing nightlies should Just Work. Let us know how it goes!

**Comment by japaric** [comment]
I finally cross-compiled rust on Debian Wheezy but for some reason the resulting binary ended with a dependency of glibc-2.15! :cry: So it doesn't run in the raspbian chroot. I'm not sure what went wrong there, since Wheezy has a glibc-2.13 package, so I'm thinking that the arm cross-compiler (and its runtime) may have injected symbols that depend on glibc-2.15.

@plugwash Let me barrage you with questions!

- Have you seen this happen before when cross-compiling?
- What cross-compiler do you guys use for the raspbian packages? I used linaro 2013.04, since I couldn't find an official arm-4.7-g++ package for Wheezy (is there one?).
- Or do you build the packages directly in the RPi? (That would be commendable!) (Even if that's the case, you had to dealt with cross-compiling at some point)

**Comment by plugwash** [comment]
On 03/02/15 14:29, Jorge Aparicio wrote:
>
> I finally cross-compiled rust on Debian Wheezy but for some reason the 
> resulting binary ended with a dependency of glibc-2.15! :cry: So it 
> doesn't run in the raspbian chroot. I'm not sure what went wrong 
> there, since Wheezy has a glibc-2.13 package, so I'm thinking that the 
> arm cross-compiler (and its runtime) may have injected symbols that 
> depend on glibc-2.15.
>
I would guess your cross-compiler is using an armhf glibc that didn't 
come from debian or raspbian wheezy and it newer than the version in 
debian wheezy.
>
> @plugwash <https://github.com/plugwash> Let me barrage you with questions!
>
>     * Have you seen this happen before when cross-compiling?
>
No but then every time i've tried cross-comiling i've come to the 
conclusion it's more trouble than it's worth.

I'm sure I would think differently if I knew I was going to be building 
the same large program over and over rather than building lots of 
different things.
>
>     * What cross-compiler do you guys use for the raspbian packages?
>       Or do you build the packages directly in the RPi? (That would be
>       commendable!)
>
We build natively on arm hardware but not on Pis.

 >I used linaro 2013.04, since I couldn't find an official arm-4.7-g++ 
package for Wheezy (is there one?).
Not in Debian itself, there are toolchains on emdebian.org 
http://www.emdebian.org/debian/

>     * (Even if that's the case, you had to dealt with cross-compiling
>       at some point)
>
Actually we didn't, we started from Debian armhf, rebuilt gcc with 
chaged defaults and then started rebuilding stuff (sometimes more than 
once) until we got a sufficient number of armv7-free packages to set up 
a repository and buildds.

**Comment by japaric** [comment]
@plugwash `\o/` the emdebian toolchain finally did the trick. Thank you so much for the pointers :+1: (Oh, and I agree about cross-compiling being more trouble than it's worth it)

@Novacha @shavounet Could you give a try to the following nightly?

```
old_snapshots/rust-2015-01-27-7774359-arm-unknown-linux-gnueabihf-38d…8643ef5ca6e2.tar.gz
```

It was cross compiled from my laptop, and it works with my ARM board in a Raspbian chroot. I'm currently using it to natively build a new rust nightly inside the Raspbian chroot.

**Comment by Novacha** [comment]
@japaric Thanks for the effort you have put into building this! I unfortunately get the following error:

```
$ LD_LIBRARY_PATH=$LD_LIBRARY_PATH:lib bin/rustc -V
Illegal instruction
```

**Comment by japaric** [comment]
@Novacha hah, I was sort of expecting that to happen. Could you try to get more information from this? Does `RUST_BACKTRACE=1` work? If not maybe try running `rustc` via `gdb`.

I think this can be solved by passing some extras flags to LLVM telling it to codegen instructions that the RPi can run. I need to look into LLVM codegen options first.

**Comment by japaric** [comment]
@Novacha, @shavounet Could you try this stage0 snapshot:

```
snaphots/rust-stage0-2015-01-28-a45e117-linux-arm-7b087263fb98935…a2557d546c.tar.bz2
```

You can run it without setting `LD_LIBRARY_PATH`, just run `bin/rustc` directly. The snapshot can't do much, but either `rustc -V` or compiling a file with just `#![no_std] #![crate_type = "lib"]` should work.

That snapshot was compiled in the Raspbian chroot, and AFAIK our `rustc` passes `-cpu=generic, -mattr=+v6,+vfp2` to LLVM, which should be OK for the RPi (ARMv6 and VFP2 floating point engine, right?), and the LLVM that's statically linked in the snapshot was built with a `gcc` configured with `--with-arch=armv6 --with-fpu=vfp` which should also be OK for the RPi.

If it still doesn't work, then... I'm not sure what else could be.

**Comment by Novacha** [comment]
@japaric With `RUST_BACKTRACE=1`, the error is still the same:

```
$ LD_LIBRARY_PATH=$LD_LIBRARY_PATH:lib RUST_BACKTRACE=1 bin/rustc -V
Illegal instruction
```

The new snapshot worked though :+1:!

```
$ rust-stage0/bin/rustc -V
rustc 1.0.0-dev (a45e11773 2015-01-28 11:01:36 +0000)
```

**Comment by japaric** [comment]
> The new snapshot worked though :+1:!

A good omen! I just uploaded a new nightly `rust-2015-02-02-eaf4c5c-arm-unknown-linux-gnueabihf-24fd…f6b663278a59.tar.gz` that was built in the Raspbian chroot using the snapshot that you just tried. Please give it a go and let me know if it works. You need LD_LIBRARY_PATH and can use all the usual crates (std and friends).

**Comment by Novacha** [comment]
@japaric It works :tada:!

```
$ LD_LIBRARY_PATH=$LD_LIBRARY_PATH:lib bin/rustc -V
rustc 1.0.0-dev (eaf4c5c78 2015-02-02 15:04:54 +0000)
```

Building a sample "Hello World" program:

```
$ LD_LIBRARY_PATH=$LD_LIBRARY_PATH:lib bin/rustc hello.rs
$ ./hello
Hello World
```

**Comment by japaric** [comment]
Finally! :joy: 

I'm building a cargo nightly right now, I'll ping you when it's ready. :wink:

**Comment by japaric** [comment]
Cargo nightly is up (the one in the root of the folder). Please try building some cargo package with it as a smoke test, you can even try building cargo with it! (It may take several minutes though)

**Comment by Novacha** [comment]
@japaric Cargo version :+1: :

```
$ bin/cargo -V
cargo 0.0.1-pre (0557065 2015-02-04 23:00:30 +0000)
```

Building the default cargo hello world :+1: :

```
$ cargo new --bin HelloWorld
$ cd HelloWorld
$ cargo build -v
   Compiling HelloWorld v0.0.1 (file:///home/pi/ruststrap/Projects/HelloWorld)
     Running `rustc src/main.rs --crate-name HelloWorld --crate-type bin -g --out-dir /home/pi/ruststrap/Projects/HelloWorld/target --emit=dep-info,link -L dependency=/home/pi/ruststrap/Projects/HelloWorld/target -L dependency=/home/pi/ruststrap/Projects/HelloWorld/target/deps`
$ cargo run
     Running `target/HelloWorld`
Hello, world!
```

Right now i'm building the `hello world` iron webserver example ([iron/examples/hello.rs](https://github.com/iron/iron/blob/8c4eb2997c20d4fcd2aece5010b015d4260953a3/examples/hello.rs)), though it looks like it will take a while for it to finish compiling all the dependencies. Thanks for all the great work!

**Comment by japaric** [comment]
Looks like we are done here :-). Thanks everyone for your help! If you any find any problem with the nighlies, please open a new issue.

**Comment by Novacha** [comment]
Just a final note, the Iron example compiled, linked and ran successfully.

**Comment by shavounet** [comment]
Just to let you know : it is also working fine for me !
I'll try to build it on my pi now :-)
Thanks for all !
