### ISSUE TITLE
librustc_driver not found

### ISSUE THREAD

**Issue by jonalmeida** [japaric/ruststrap#27]
After taking a compiled binary, putting it on a fresh install of Raspbian, I get this error. Below are my configurations & details:

**Raspbian image:** `2015-01-31-raspbian.img`

**Rust binary tar file:** 
 - `rust-2015-02-04-ba2f13e-arm-unknown-linux-gnueabihf-7a8b26699603fc6ce4ea9e76f7eed956b89f09e4`
 - `rust-2015-02-06-d3732a1-arm-unknown-linux-gnueabihf-5bbd74fe28f43af38464b66b59c85647ae20a3b0.tar.gz`

**Binary location:**
> pi@raspberrypi ~/rust/bin $ ls
rust-gdb  rustc  rustdoc
pi@raspberrypi ~/rust/bin $ pwd
/home/pi/rust/bin

**PATH**:
> pi@raspberrypi ~/rust $ echo $PATH
/home/pi/rust/bin:/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin:/usr/local/games:/usr/games

**Output from execution:**
> pi@raspberrypi ~/rust $ rustc --version
rustc: error while loading shared libraries: librustc_driver-4e7c5e5c.so: cannot open shared object file: No such file or directory

Great work with the build scripts! :)

EDIT: Updated with two builds that don't work.

**Comment by Novacha** [comment]
You will need to specify the library path (the `lib` folder next to the `bin` folder). This means that you should be able to run the following command:

```
LD_LIBRARY_PATH=$LD_LIBRARY_PATH:lib bin/rustc -V
```

where `rustc` is located at `bin/rustc`.

**Comment by jonalmeida** [comment]
Ah yes! I forgot to do that. Thanks @Novacha !

Closing..
