### ISSUE TITLE
Typo

### ISSUE THREAD

**Issue by theWebalyst** [japaric/ruststrap#38]
Thanks for this, it worked a treat. 

Note: the following line from https://github.com/japaric/ruststrap/blob/master/1-how-to-cross-compile.md contains a typo "uknown"...

$ rustc --target=arm-uknown-linux-gnueabihf lib.rs && ls lib*

**Comment by japaric** [comment]
> Thanks for this, it worked a treat. 

You are welcome!

Fixed the typo in 8a59dc3.
