### ISSUE TITLE
Fix for package name for cross-compilation x86-64 to x86

### ISSUE THREAD

**Issue by ERnsTL** [japaric/ruststrap#40]
Greetings, in your file 1-... .md you write about missing libraries when compiling x86 Rust binaries on x86-64, quote:

> you'll need to install the libc-dev:i386 package on Debian/Ubuntu to fix that error.

At least on Ubuntu 14.04 LTS, the package which contains the 32-bit versions of required libraries is correctly called ```libc6-dev-i386```, not ```libc-dev:i386``` and most importantly NOT with the suffix ```:i386```.

(```:i386``` would replace the installed native amd64 versions and thus produces install conflicts and will abort whereas ```-i386``` is for cross-compilation. And it' called ```libc6```, not ```libc``` for some reason, at least on Ubuntu 14.04.)

So, ```libc6-dev-i386``` is the one that fixes the issue. Small change, but cost me over an hour searching. Please update in your .md file, maybe somebody else also wants to do cross-compiling 64bit to 32bit.

Thanks.

**Comment by japaric** [comment]
Thanks for the report.
