### ISSUE TITLE
What happened to the binary builds?

### ISSUE THREAD

**Issue by petevine** [japaric/ruststrap#42]
Hope you're ok...

**Comment by warricksothr** [comment]
I'm not sure what happened to him. But I used his scripts as a base design for a build system and have started publishing new nightlies. My system is slightly different and my build parameters are slightly different as well so I haven't just forked this project. https://github.com/warricksothr/RustBuild

**Comment by petevine** [comment]
Are you going to provide full binary builds like japaric used to?

**Comment by warricksothr** [comment]
That's the plan. I have the last 2 days of builds up right now. Still stabilizing my nightly build process, and once that's done it'll be completely automated.

**Comment by petevine** [comment]
Great, thx! Looks like japaric has called it a day.
